name: MERN CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Backend
        run: |
          cd backend
          npm install

      - name: Install Frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Build Backend Docker Image
        run: |
          cd backend
          docker build -t pranavvengatesh191103/mern-backend .

      - name: Build Frontend Docker Image
        run: |
          cd frontend
          docker build -t pranavvengatesh191103/mern-frontend .
